var __createBinding=this&&this.__createBinding||(Object.create?function(c,f,e,k){void 0===k&&(k=e);var g=Object.getOwnPropertyDescriptor(f,e);if(!g||("get"in g?!f.__esModule:g.writable||g.configurable))g={enumerable:!0,get:function(){return f[e]}};Object.defineProperty(c,k,g)}:function(c,f,e,k){void 0===k&&(k=e);c[k]=f[e]}),__setModuleDefault=this&&this.__setModuleDefault||(Object.create?function(c,f){Object.defineProperty(c,"default",{enumerable:!0,value:f})}:function(c,f){c["default"]=f}),__importStar=
this&&this.__importStar||function(){var c=function(f){c=Object.getOwnPropertyNames||function(e){var k=[],g;for(g in e)Object.prototype.hasOwnProperty.call(e,g)&&(k[k.length]=g);return k};return c(f)};return function(f){if(f&&f.__esModule)return f;var e={};if(null!=f)for(var k=c(f),g=0;g<k.length;g++)"default"!==k[g]&&__createBinding(e,f,k[g]);__setModuleDefault(e,f);return e}}();Object.defineProperty(exports,"__esModule",{value:!0});
exports.decodeBinaryNode=exports.decodeDecompressedBinaryNode=exports.decompressingIfRequired=void 0;const util_1=require("util"),zlib_1=require("zlib"),constants=__importStar(require("./constants")),jid_utils_1=require("./jid-utils"),inflatePromise=(0,util_1.promisify)(zlib_1.inflate),decompressingIfRequired=async c=>c=2&c.readUInt8()?await inflatePromise(c.slice(1)):c.slice(1);exports.decompressingIfRequired=decompressingIfRequired;
const decodeDecompressedBinaryNode=(c,f,e={index:0})=>{const {DOUBLE_BYTE_TOKENS:k,SINGLE_BYTE_TOKENS:g,TAGS:d}=f,u=a=>{if(e.index+a>c.length)throw Error("end of stream");},t=()=>{const a=c[e.index];e.index+=1;return a},l=()=>{u(1);return t()},q=a=>{u(a);const b=c.slice(e.index,e.index+a);e.index+=a;return b},w=(a,b=!1)=>{u(a);let h=0;for(let n=0;n<a;n++){const v=b?n:a-1-n;h|=t()<<8*v}return h},z=()=>{u(3);return((t()&15)<<16)+(t()<<8)+t()},D=a=>{if(0<=a&&9>=a)return 48+a;switch(a){case 10:return 45;
case 11:return 46;case 15:return 0;default:throw Error("invalid nibble: "+a);}},A=(a,b)=>{if(a===d.NIBBLE_8)return D(b);if(a===d.HEX_8){if(!(0<=b&&16>b))throw Error("invalid hex: "+b);return 10>b?48+b:65+b-10}throw Error("unknown tag: "+a);},B=a=>{switch(a){case d.LIST_EMPTY:return 0;case d.LIST_8:return l();case d.LIST_16:return w(2);default:throw Error("invalid tag for list size: "+a);}},p=a=>{if(1<=a&&a<g.length)return g[a]||"";switch(a){case d.DICTIONARY_0:case d.DICTIONARY_1:case d.DICTIONARY_2:case d.DICTIONARY_3:var b=
a-d.DICTIONARY_0;a=l();var h=k[b];if(!h)throw Error(`Invalid double token dict (${b})`);b=h[a];if("undefined"===typeof b)throw Error(`Invalid double token (${a})`);return b;case d.LIST_EMPTY:return"";case d.BINARY_8:return q(l()).toString("utf-8");case d.BINARY_20:return q(z()).toString("utf-8");case d.BINARY_32:return q(w(4)).toString("utf-8");case d.JID_PAIR:a=p(l());if(b=p(l()))a=(a||"")+"@"+b;else throw Error("invalid jid pair: "+a+", "+b);return a;case d.AD_JID:return a=l(),a=Number(a),b=l(),
h=p(l()),(0,jid_utils_1.jidEncode)(h,0===a||128===a?"s.whatsapp.net":"lid",b);case d.HEX_8:case d.NIBBLE_8:b=l();h="";for(let n=0;n<(b&127);n++){const v=l();h+=String.fromCharCode(A(a,(v&240)>>4));h+=String.fromCharCode(A(a,v&15))}0!==b>>7&&(h=h.slice(0,-1));return h;default:throw Error("invalid string with tag: "+a);}};var r=a=>{const b=[];a=B(a);for(let h=0;h<a;h++)b.push((0,exports.decodeDecompressedBinaryNode)(c,f,e));return b},m=B(l());const x=p(l());if(!m||!x.length)throw Error("invalid node");
const C={};let y;if(0===m||!x)throw Error("invalid node");const E=m-1>>1;for(let a=0;a<E;a++){const b=p(l()),h=p(l());C[b]=h}if(0===m%2)if(m=l(),m===d.LIST_EMPTY||m===d.LIST_8||m===d.LIST_16)y=r(m);else{switch(m){case d.BINARY_8:r=q(l());break;case d.BINARY_20:r=q(z());break;case d.BINARY_32:r=q(w(4));break;default:r=p(m)}y=r}return{tag:x,attrs:C,content:y}};exports.decodeDecompressedBinaryNode=decodeDecompressedBinaryNode;
const decodeBinaryNode=async c=>{c=await (0,exports.decompressingIfRequired)(c);return(0,exports.decodeDecompressedBinaryNode)(c,constants)};exports.decodeBinaryNode=decodeBinaryNode;
