var __createBinding=this&&this.__createBinding||(Object.create?function(f,d,c,h){void 0===h&&(h=c);var b=Object.getOwnPropertyDescriptor(d,c);if(!b||("get"in b?!d.__esModule:b.writable||b.configurable))b={enumerable:!0,get:function(){return d[c]}};Object.defineProperty(f,h,b)}:function(f,d,c,h){void 0===h&&(h=c);f[h]=d[c]}),__setModuleDefault=this&&this.__setModuleDefault||(Object.create?function(f,d){Object.defineProperty(f,"default",{enumerable:!0,value:d})}:function(f,d){f["default"]=d}),__importStar=
this&&this.__importStar||function(){var f=function(d){f=Object.getOwnPropertyNames||function(c){var h=[],b;for(b in c)Object.prototype.hasOwnProperty.call(c,b)&&(h[h.length]=b);return h};return f(d)};return function(d){if(d&&d.__esModule)return d;var c={};if(null!=d)for(var h=f(d),b=0;b<h.length;b++)"default"!==h[b]&&__createBinding(c,d,h[b]);__setModuleDefault(c,d);return c}}();Object.defineProperty(exports,"__esModule",{value:!0});exports.encodeBinaryNode=void 0;
const constants=__importStar(require("./constants")),jid_utils_1=require("./jid-utils"),encodeBinaryNode=(f,d=constants,c=[0])=>{f=encodeBinaryNodeInner(f,d,c);return Buffer.from(f)};exports.encodeBinaryNode=encodeBinaryNode;
const encodeBinaryNodeInner=({tag:f,attrs:d,content:c},h,b)=>{const {TAGS:k,TOKEN_MAP:v}=h,w=(a,e,g=!1)=>{for(let l=0;l<e;l++)b.push(a>>8*(g?l:e-1-l)&255)},n=a=>{for(const e of a)b.push(e)},q=a=>{if(4294967296<=a)throw Error("string too large to encode: "+a);1048576<=a?(b.push(k.BINARY_32&255),w(a,4)):256<=a?(b.push(k.BINARY_20&255),n([a>>16&15,a>>8&255,a&255])):(b.push(k.BINARY_8&255),b.push(a&255))},x=({domainType:a,device:e,user:g,server:l})=>{"undefined"!==typeof e?(b.push(k.AD_JID&255),b.push((a||
0)&255),b.push((e||0)&255),m(g)):(b.push(k.JID_PAIR&255),g.length?m(g):b.push(k.LIST_EMPTY&255),m(l))},y=a=>{switch(a){case "-":return 10;case ".":return 11;case "\x00":return 15;default:if("0"<=a&&"9">=a)return a.charCodeAt(0)-48;throw Error(`invalid byte for nibble "${a}"`);}},z=a=>{if("0"<=a&&"9">=a)return a.charCodeAt(0)-48;if("A"<=a&&"F">=a)return 10+a.charCodeAt(0)-65;if("a"<=a&&"f">=a)return 10+a.charCodeAt(0)-97;if("\x00"===a)return 15;throw Error(`Invalid hex char "${a}"`);},r=(a,e)=>{if(a.length>
k.PACKED_MAX)throw Error("Too many bytes to pack");b.push(("nibble"===e?k.NIBBLE_8:k.HEX_8)&255);var g=Math.ceil(a.length/2);0!==a.length%2&&(g|=128);b.push(g&255);e="nibble"===e?y:z;g=Math.floor(a.length/2);for(let p=0;p<g;p++){var l=a[2*p+1];l=e(a[2*p])<<4|e(l);b.push(l&255)}0!==a.length%2&&(a=e(a[a.length-1])<<4|e("\x00"),b.push(a&255))},m=a=>{if(void 0===a||null===a)b.push(k.LIST_EMPTY&255);else{var e=v[a];if(e)"number"===typeof e.dict&&b.push(k.DICTIONARY_0+e.dict&255),b.push(e.index&255);else{a:if(!a||
a.length>k.PACKED_MAX)e=!1;else{for(const l of a)if(!("0"<=l&&"9">=l)&&"-"!==l&&"."!==l){e=!1;break a}e=!0}if(e)r(a,"nibble");else{a:if(!a||a.length>k.PACKED_MAX)var g=!1;else{for(g of a)if(!("0"<=g&&"9">=g||"A"<=g&&"F">=g)){g=!1;break a}g=!0}g?r(a,"hex"):a&&((g=(0,jid_utils_1.jidDecode)(a))?x(g):(a=Buffer.from(a,"utf-8"),q(a.length),n(a)))}}}},t=a=>{0===a?b.push(k.LIST_EMPTY&255):256>a?n([k.LIST_8,a]):(b.push(k.LIST_16&255),n([a>>8&255,a&255]))};if(!f)throw Error("Invalid node: tag cannot be undefined");
const u=Object.keys(d||{}).filter(a=>"undefined"!==typeof d[a]&&null!==d[a]);t(2*u.length+1+("undefined"!==typeof c?1:0));m(f);for(const a of u)"string"===typeof d[a]&&(m(a),m(d[a]));if("string"===typeof c)m(c);else if(Buffer.isBuffer(c)||c instanceof Uint8Array)q(c.length),n(c);else if(Array.isArray(c)){f=c.filter(a=>a&&(a.tag||Buffer.isBuffer(a)||a instanceof Uint8Array||"string"===typeof a));t(f.length);for(const a of f)encodeBinaryNodeInner(a,h,b)}else if("undefined"!==typeof c)throw Error(`invalid children for header "${f}": ${c} (${typeof c})`);
return b};
