var __importDefault=this&&this.__importDefault||function(m){return m&&m.__esModule?m:{"default":m}};Object.defineProperty(exports,"__esModule",{value:!0});exports.makeChatsSocket=void 0;
const node_cache_1=__importDefault(require("@cacheable/node-cache")),boom_1=require("@hapi/boom"),WAProto_1=require("../../WAProto"),Defaults_1=require("../Defaults"),Types_1=require("../Types"),Utils_1=require("../Utils"),make_mutex_1=require("../Utils/make-mutex"),process_message_1=__importDefault(require("../Utils/process-message")),WABinary_1=require("../WABinary"),WAUSync_1=require("../WAUSync"),usync_1=require("./usync"),MAX_SYNC_ATTEMPTS=2,makeChatsSocket=m=>{const {logger:l,markOnlineOnConnect:V,
fireInitQueries:W,appStateMacVerification:I,shouldIgnoreJid:X,shouldSyncHistoryMessage:Y}=m,A=(0,usync_1.makeUSyncSocket)(m),{ev:p,ws:F,authState:f,generateMessageTag:J,sendNode:C,query:r,onUnexpectedError:K}=A;let G,L=!1,D=!1;const M=(0,make_mutex_1.makeMutex)(),N=m.placeholderResendCache||new node_cache_1.default({stdTTL:Defaults_1.DEFAULT_CACHE_TTLS.MSG_RETRY,useClones:!1});m.placeholderResendCache||(m.placeholderResendCache=N);const E=async a=>{({[a]:a}=await f.keys.get("app-state-sync-key",[a]));
return a},O=async(a=!1)=>{if(!G||a)({content:a}=await r({tag:"iq",attrs:{xmlns:"privacy",to:WABinary_1.S_WHATSAPP_NET,type:"get"},content:[{tag:"privacy",attrs:{}}]})),G=(0,WABinary_1.reduceBinaryNodeToDictionary)(null===a||void 0===a?void 0:a[0],"category");return G},u=async(a,b)=>{await r({tag:"iq",attrs:{xmlns:"privacy",to:WABinary_1.S_WHATSAPP_NET,type:"set"},content:[{tag:"privacy",attrs:{},content:[{tag:"category",attrs:{name:a,value:b}}]}]})},P=async()=>{var a=await r({tag:"iq",attrs:{xmlns:"blocklist",
to:WABinary_1.S_WHATSAPP_NET,type:"get"}});a=(0,WABinary_1.getBinaryNodeChild)(a,"list");return(0,WABinary_1.getBinaryNodeChildren)(a,"item").map(b=>b.attrs.jid)},Q=async(a,b)=>{l.info({fromTimestamp:b},"clean dirty bits "+a);await C({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"urn:xmpp:whatsapp:dirty",id:J()},content:[{tag:"clean",attrs:{type:a,...(b?{timestamp:b.toString()}:null)}}]})},R=a=>({onMutation(b){(0,Utils_1.processSyncAction)(b,p,f.creds.me,a?{accountSettings:f.creds.accountSettings}:
void 0,l)}}),H=p.createBufferedFunction(async(a,b)=>{const c={},d={};await f.keys.transaction(async()=>{var g;const h=new Set(a),k={};for(;h.size;){const y={};var n=[];for(const t of h){var e=(await f.keys.get("app-state-sync-version",[t]))[t];e?"undefined"===typeof c[t]&&(c[t]=e.version):e=(0,Utils_1.newLTHashState)();y[t]=e;l.info(`resyncing ${t} from v${e.version}`);n.push({tag:"collection",attrs:{name:t,version:e.version.toString(),return_snapshot:(!e.version).toString()}})}n=await r({tag:"iq",
attrs:{to:WABinary_1.S_WHATSAPP_NET,xmlns:"w:sync:app:state",type:"set"},content:[{tag:"sync",attrs:{},content:n}]});n=await (0,Utils_1.extractSyncdPatches)(n,null===m||void 0===m?void 0:m.options);for(const t in n){e=t;const {patches:z,hasMorePatches:B,snapshot:v}=n[e];try{if(v){const {state:q,mutationMap:w}=await (0,Utils_1.decodeSyncdSnapshot)(e,v,E,c[e],I.snapshot);y[e]=q;Object.assign(d,w);l.info(`restored state of ${e} from snapshot to v${q.version} with mutations`);await f.keys.set({"app-state-sync-version":{[e]:q}})}if(z.length){const {state:q,
mutationMap:w}=await (0,Utils_1.decodePatches)(e,z,y[e],E,m.options,c[e],l,I.patch);await f.keys.set({"app-state-sync-version":{[e]:q}});l.info(`synced ${e} to v${q.version}`);c[e]=q.version;Object.assign(d,w)}B?l.info(`${e} has more patches...`):h.delete(e)}catch(q){const w=k[e]>=MAX_SYNC_ATTEMPTS||404===(null===(g=q.output)||void 0===g?void 0:g.statusCode)||"TypeError"===q.name;l.info({name:e,error:q.stack},`failed to sync state from version${w?"":", removing and trying from scratch"}`);await f.keys.set({"app-state-sync-version":{[e]:null}});
k[e]=(k[e]||0)+1;w&&h.delete(e)}}}});({onMutation:b}=R(b));for(const g in d)b(d[g])}),S=async(a,b)=>{const c=f.creds.me;"available"===a||"unavailable"===a?c.name?(p.emit("connection.update",{isOnline:"available"===a}),await C({tag:"presence",attrs:{name:c.name,type:a}})):l.warn("no name present, ignoring presence update request..."):await C({tag:"chatstate",attrs:{from:c.id,to:b},content:[{tag:"recording"===a?"composing":a,attrs:"recording"===a?{media:"audio"}:{}}]})},T=({tag:a,attrs:b,content:c})=>
{var d;let g;const h=b.from,k=b.participant||b.from;X(h)&&"@s.whatsapp.net"!==h||("presence"===a?g={lastKnownPresence:"unavailable"===b.type?"unavailable":"available",lastSeen:b.last&&"deny"!==b.last?+b.last:void 0}:Array.isArray(c)?([a]=c,b=a.tag,"paused"===b&&(b="available"),"audio"===(null===(d=a.attrs)||void 0===d?void 0:d.media)&&(b="recording"),g={lastKnownPresence:b}):l.error({tag:a,attrs:b,content:c},"recv invalid presence node"),g&&p.emit("presence.update",{id:h,presences:{[k]:g}}))},U=async a=>
{const b=a.type,c=f.creds.myAppStateKeyId;if(!c)throw new boom_1.Boom("App state key not present!",{statusCode:400});let d,g;await M.mutex(async()=>{await f.keys.transaction(async()=>{l.debug({patch:a},"applying app patch");await H([b],!1);var {[b]:h}=await f.keys.get("app-state-sync-version",[b]);d=h||(0,Utils_1.newLTHashState)();g=await (0,Utils_1.encodeSyncdPatch)(a,c,d,E);const {patch:k,state:n}=g;h={tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"w:sync:app:state"},content:[{tag:"sync",
attrs:{},content:[{tag:"collection",attrs:{name:b,version:(n.version-1).toString(),return_snapshot:"false"},content:[{tag:"patch",attrs:{},content:WAProto_1.proto.SyncdPatch.encode(k).finish()}]}]}]};await r(h);await f.keys.set({"app-state-sync-version":{[b]:n}})})});if(m.emitOwnEvents){const {onMutation:h}=R(!1),{mutationMap:k}=await (0,Utils_1.decodePatches)(b,[{...g.patch,version:{version:g.state.version}}],d,E,m.options,void 0,l);for(const n in k)h(k[n])}},Z=async()=>{var a,b,c,d=await r({tag:"iq",
attrs:{to:WABinary_1.S_WHATSAPP_NET,xmlns:"w",type:"get"},content:[{tag:"props",attrs:{protocol:"2",hash:(null===(a=null===f||void 0===f?void 0:f.creds)||void 0===a?void 0:a.lastPropHash)||""}}]});a=(0,WABinary_1.getBinaryNodeChild)(d,"props");d={};if(a){if(null===(b=a.attrs)||void 0===b?0:b.hash)f.creds.lastPropHash=null===(c=null===a||void 0===a?void 0:a.attrs)||void 0===c?void 0:c.hash,p.emit("creds.update",f.creds);d=(0,WABinary_1.reduceBinaryNodeToDictionary)(a,"prop")}l.debug("fetched props");
return d},x=(a,b)=>{a=(0,Utils_1.chatModificationToAppPatch)(a,b);return U(a)},aa=async()=>{await Promise.all([Z(),P(),O()])},ba=p.createBufferedFunction(async(a,b)=>{async function c(){f.creds.accountSyncCounter||(l.info("doing initial app state sync"),await H(Types_1.ALL_WA_PATCH_NAMES,!0),p.emit("creds.update",{accountSyncCounter:(f.creds.accountSyncCounter||0)+1}),L&&(l.debug("flushing with app state sync"),p.flush()))}var d,g,h;p.emit("messages.upsert",{messages:[a],type:b});a.pushName&&(b=a.key.fromMe?
f.creds.me.id:a.key.participant||a.key.remoteJid,b=(0,WABinary_1.jidNormalizedUser)(b),a.key.fromMe||p.emit("contacts.update",[{id:b,notify:a.pushName,verifiedName:a.verifiedBizName}]),a.key.fromMe&&a.pushName&&(null===(d=f.creds.me)||void 0===d?void 0:d.name)!==a.pushName&&p.emit("creds.update",{me:{...f.creds.me,name:a.pushName}}));const k=(0,Utils_1.getHistoryMsg)(a.message);d=k?Y(k)&&Defaults_1.PROCESSABLE_HISTORY_TYPES.includes(k.syncType):!1;k&&!f.creds.myAppStateKeyId&&(l.warn("skipping app state sync, as myAppStateKeyId is not set"),
D=!0);await Promise.all([(async()=>{k&&f.creds.myAppStateKeyId&&(D=!1,await c())})(),(0,process_message_1.default)(a,{shouldProcessHistoryMsg:d,placeholderResendCache:N,ev:p,creds:f.creds,keyStore:f.keys,logger:l,options:m.options})]);(null===(h=null===(g=a.message)||void 0===g?void 0:g.protocolMessage)||void 0===h?0:h.appStateSyncKeyShare)&&D&&(await c(),D=!1)});F.on("CB:presence",T);F.on("CB:chatstate",T);F.on("CB:ib,,dirty",async a=>{const {attrs:b}=(0,WABinary_1.getBinaryNodeChild)(a,"dirty");
switch(b.type){case "account_sync":b.timestamp&&({lastAccountSyncTimestamp:a}=f.creds,a&&await Q("account_sync",a),a=+b.timestamp,p.emit("creds.update",{lastAccountSyncTimestamp:a}));break;case "groups":break;default:l.info({node:a},"received unknown sync")}});p.on("connection.update",({connection:a,receivedPendingNotifications:b})=>{var c;"open"===a&&(W&&aa().catch(d=>K(d,"init queries")),S(V?"available":"unavailable").catch(d=>K(d,"presence update requests")));!b||null!==(c=f.creds)&&void 0!==c&&
c.myAppStateKeyId||(p.buffer(),L=!0)});return{...A,getBotListV2:async()=>{var a=await r({tag:"iq",attrs:{xmlns:"bot",to:WABinary_1.S_WHATSAPP_NET,type:"get"},content:[{tag:"bot",attrs:{v:"2"}}]});a=(0,WABinary_1.getBinaryNodeChild)(a,"bot");const b=[];for(const c of(0,WABinary_1.getBinaryNodeChildren)(a,"section"))if("all"===c.attrs.type)for(const d of(0,WABinary_1.getBinaryNodeChildren)(c,"bot"))b.push({jid:d.attrs.jid,personaId:d.attrs.persona_id});return b},processingMutex:M,fetchPrivacySettings:O,
upsertMessage:ba,appPatch:U,sendPresenceUpdate:S,presenceSubscribe:(a,b)=>C({tag:"presence",attrs:{to:a,id:J(),type:"subscribe"},content:b?[{tag:"tctoken",attrs:{},content:b}]:void 0}),profilePictureUrl:async(a,b="preview",c)=>{var d;a=(0,WABinary_1.jidNormalizedUser)(a);a=await r({tag:"iq",attrs:{target:a,to:WABinary_1.S_WHATSAPP_NET,type:"get",xmlns:"w:profile:picture"},content:[{tag:"picture",attrs:{type:b,query:"url"}}]},c);a=(0,WABinary_1.getBinaryNodeChild)(a,"picture");return null===(d=null===
a||void 0===a?void 0:a.attrs)||void 0===d?void 0:d.url},onWhatsApp:async(...a)=>{var b=(new WAUSync_1.USyncQuery).withContactProtocol().withLIDProtocol();for(const c of a)a=`+${c.replace("+","").split("@")[0].split(":")[0]}`,b.withUser((new WAUSync_1.USyncUser).withPhone(a));if(b=await A.executeUSyncQuery(b))return b.list.filter(c=>!!c.contact).map(({contact:c,id:d,lid:g})=>({jid:d,exists:c,lid:g}))},fetchBlocklist:P,fetchStatus:async(...a)=>{const b=(new WAUSync_1.USyncQuery).withStatusProtocol();
for(const c of a)b.withUser((new WAUSync_1.USyncUser).withId(c));if(a=await A.executeUSyncQuery(b))return a.list},fetchDisappearingDuration:async(...a)=>{const b=(new WAUSync_1.USyncQuery).withDisappearingModeProtocol();for(const c of a)b.withUser((new WAUSync_1.USyncUser).withId(c));if(a=await A.executeUSyncQuery(b))return a.list},updateProfilePicture:async(a,b)=>{let c;if(!a)throw new boom_1.Boom("Illegal no-jid profile update. Please specify either your ID or the ID of the chat you wish to update");
(0,WABinary_1.jidNormalizedUser)(a)!==(0,WABinary_1.jidNormalizedUser)(f.creds.me.id)&&(c=(0,WABinary_1.jidNormalizedUser)(a));({img:a}=await (0,Utils_1.generateProfilePicture)(b));await r({tag:"iq",attrs:{target:c,to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"w:profile:picture"},content:[{tag:"picture",attrs:{type:"image"},content:a}]})},removeProfilePicture:async a=>{let b;if(!a)throw new boom_1.Boom("Illegal no-jid profile update. Please specify either your ID or the ID of the chat you wish to update");
(0,WABinary_1.jidNormalizedUser)(a)!==(0,WABinary_1.jidNormalizedUser)(f.creds.me.id)&&(b=(0,WABinary_1.jidNormalizedUser)(a));await r({tag:"iq",attrs:{target:b,to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"w:profile:picture"}})},updateProfileStatus:async a=>{await r({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,type:"set",xmlns:"status"},content:[{tag:"status",attrs:{},content:Buffer.from(a,"utf-8")}]})},updateProfileName:async a=>{await x({pushNameSetting:a},"")},updateBlockStatus:async(a,b)=>
{await r({tag:"iq",attrs:{xmlns:"blocklist",to:WABinary_1.S_WHATSAPP_NET,type:"set"},content:[{tag:"item",attrs:{action:b,jid:a}}]})},updateCallPrivacy:async a=>{await u("calladd",a)},updateMessagesPrivacy:async a=>{await u("messages",a)},updateLastSeenPrivacy:async a=>{await u("last",a)},updateOnlinePrivacy:async a=>{await u("online",a)},updateProfilePicturePrivacy:async a=>{await u("profile",a)},updateStatusPrivacy:async a=>{await u("status",a)},updateReadReceiptsPrivacy:async a=>{await u("readreceipts",
a)},updateGroupsAddPrivacy:async a=>{await u("groupadd",a)},updateDefaultDisappearingMode:async a=>{await r({tag:"iq",attrs:{xmlns:"disappearing_mode",to:WABinary_1.S_WHATSAPP_NET,type:"set"},content:[{tag:"disappearing_mode",attrs:{duration:a.toString()}}]})},getBusinessProfile:async a=>{var b,c,d,g,h,k,n;a=await r({tag:"iq",attrs:{to:"s.whatsapp.net",xmlns:"w:biz",type:"get"},content:[{tag:"business_profile",attrs:{v:"244"},content:[{tag:"profile",attrs:{jid:a}}]}]});a=(0,WABinary_1.getBinaryNodeChild)(a,
"business_profile");if(a=(0,WABinary_1.getBinaryNodeChild)(a,"profile")){const y=(0,WABinary_1.getBinaryNodeChild)(a,"address"),t=(0,WABinary_1.getBinaryNodeChild)(a,"description");var e=(0,WABinary_1.getBinaryNodeChild)(a,"website");const z=(0,WABinary_1.getBinaryNodeChild)(a,"email"),B=(0,WABinary_1.getBinaryNodeChild)((0,WABinary_1.getBinaryNodeChild)(a,"categories"),"category"),v=(0,WABinary_1.getBinaryNodeChild)(a,"business_hours"),q=v?(0,WABinary_1.getBinaryNodeChildren)(v,"business_hours_config"):
void 0;e=null===(b=null===e||void 0===e?void 0:e.content)||void 0===b?void 0:b.toString();return{wid:null===(c=a.attrs)||void 0===c?void 0:c.jid,address:null===(d=null===y||void 0===y?void 0:y.content)||void 0===d?void 0:d.toString(),description:(null===(g=null===t||void 0===t?void 0:t.content)||void 0===g?void 0:g.toString())||"",website:e?[e]:[],email:null===(h=null===z||void 0===z?void 0:z.content)||void 0===h?void 0:h.toString(),category:null===(k=null===B||void 0===B?void 0:B.content)||void 0===
k?void 0:k.toString(),business_hours:{timezone:null===(n=null===v||void 0===v?void 0:v.attrs)||void 0===n?void 0:n.timezone,business_config:null===q||void 0===q?void 0:q.map(({attrs:w})=>w)}}}},resyncAppState:H,chatModify:x,cleanDirtyBits:Q,addLabel:(a,b)=>x({addLabel:{...b}},a),addChatLabel:(a,b)=>x({addChatLabel:{labelId:b}},a),removeChatLabel:(a,b)=>x({removeChatLabel:{labelId:b}},a),addMessageLabel:(a,b,c)=>x({addMessageLabel:{messageId:b,labelId:c}},a),removeMessageLabel:(a,b,c)=>x({removeMessageLabel:{messageId:b,
labelId:c}},a),star:(a,b,c)=>x({star:{messages:b,star:c}},a)}};exports.makeChatsSocket=makeChatsSocket;
