Object.defineProperty(exports,"__esModule",{value:!0});exports.extractGroupMetadata=exports.makeGroupsSocket=void 0;
const WAProto_1=require("../../WAProto"),Types_1=require("../Types"),Utils_1=require("../Utils"),WABinary_1=require("../WABinary"),chats_1=require("./chats"),makeGroupsSocket=c=>{const g=(0,chats_1.makeChatsSocket)(c),{authState:k,ev:h,query:l,upsertMessage:n}=g,e=async(a,b,d)=>l({tag:"iq",attrs:{type:b,xmlns:"w:g2",to:a},content:d}),m=async a=>{a=await e(a,"get",[{tag:"query",attrs:{request:"interactive"}}]);return(0,exports.extractGroupMetadata)(a)},p=async()=>{var a=await l({tag:"iq",attrs:{to:"@g.us",
xmlns:"w:g2",type:"get"},content:[{tag:"participating",attrs:{},content:[{tag:"participants",attrs:{}},{tag:"description",attrs:{}}]}]});const b={};if(a=(0,WABinary_1.getBinaryNodeChild)(a,"groups")){a=(0,WABinary_1.getBinaryNodeChildren)(a,"group");for(const d of a)a=(0,exports.extractGroupMetadata)({tag:"result",attrs:{},content:[d]}),b[a.id]=a}g.ev.emit("groups.update",Object.values(b));return b};g.ws.on("CB:ib,,dirty",async a=>{({attrs:a}=(0,WABinary_1.getBinaryNodeChild)(a,"dirty"));"groups"===
a.type&&(await p(),await g.cleanDirtyBits("groups"))});return{...g,groupMetadata:m,groupCreate:async(a,b)=>{const d=(0,Utils_1.generateMessageIDV2)();a=await e("@g.us","set",[{tag:"create",attrs:{subject:a,key:d},content:b.map(f=>({tag:"participant",attrs:{jid:f}}))}]);return(0,exports.extractGroupMetadata)(a)},groupLeave:async a=>{await e("@g.us","set",[{tag:"leave",attrs:{},content:[{tag:"group",attrs:{id:a}}]}])},groupUpdateSubject:async(a,b)=>{await e(a,"set",[{tag:"subject",attrs:{},content:Buffer.from(b,
"utf-8")}])},groupRequestParticipantsList:async a=>{a=await e(a,"get",[{tag:"membership_approval_requests",attrs:{}}]);a=(0,WABinary_1.getBinaryNodeChild)(a,"membership_approval_requests");return(0,WABinary_1.getBinaryNodeChildren)(a,"membership_approval_request").map(b=>b.attrs)},groupRequestParticipantsUpdate:async(a,b,d)=>{a=await e(a,"set",[{tag:"membership_requests_action",attrs:{},content:[{tag:d,attrs:{},content:b.map(f=>({tag:"participant",attrs:{jid:f}}))}]}]);a=(0,WABinary_1.getBinaryNodeChild)(a,
"membership_requests_action");d=(0,WABinary_1.getBinaryNodeChild)(a,d);return(0,WABinary_1.getBinaryNodeChildren)(d,"participant").map(f=>({status:f.attrs.error||"200",jid:f.attrs.jid}))},groupParticipantsUpdate:async(a,b,d)=>{a=await e(a,"set",[{tag:d,attrs:{},content:b.map(f=>({tag:"participant",attrs:{jid:f}}))}]);d=(0,WABinary_1.getBinaryNodeChild)(a,d);return(0,WABinary_1.getBinaryNodeChildren)(d,"participant").map(f=>({status:f.attrs.error||"200",jid:f.attrs.jid,content:f}))},groupUpdateDescription:async(a,
b)=>{var d;const f=null!==(d=(await m(a)).descId)&&void 0!==d?d:null;await e(a,"set",[{tag:"description",attrs:{...(b?{id:(0,Utils_1.generateMessageIDV2)()}:{delete:"true"}),...(f?{prev:f}:{})},content:b?[{tag:"body",attrs:{},content:Buffer.from(b,"utf-8")}]:void 0}])},groupInviteCode:async a=>{a=await e(a,"get",[{tag:"invite",attrs:{}}]);a=(0,WABinary_1.getBinaryNodeChild)(a,"invite");return null===a||void 0===a?void 0:a.attrs.code},groupRevokeInvite:async a=>{a=await e(a,"set",[{tag:"invite",attrs:{}}]);
a=(0,WABinary_1.getBinaryNodeChild)(a,"invite");return null===a||void 0===a?void 0:a.attrs.code},groupAcceptInvite:async a=>{a=await e("@g.us","set",[{tag:"invite",attrs:{code:a}}]);a=(0,WABinary_1.getBinaryNodeChild)(a,"group");return null===a||void 0===a?void 0:a.attrs.jid},groupRevokeInviteV4:async(a,b)=>!!await e(a,"set",[{tag:"revoke",attrs:{},content:[{tag:"participant",attrs:{jid:b}}]}]),groupAcceptInviteV4:h.createBufferedFunction(async(a,b)=>{var d;a="string"===typeof a?{remoteJid:a}:a;const f=
await e(b.groupJid,"set",[{tag:"accept",attrs:{code:b.inviteCode,expiration:b.inviteExpiration.toString(),admin:a.remoteJid}}]);a.id&&(b=WAProto_1.proto.Message.GroupInviteMessage.fromObject(b),b.inviteExpiration=0,b.inviteCode="",h.emit("messages.update",[{key:a,update:{message:{groupInviteMessage:b}}}]));await n({key:{remoteJid:b.groupJid,id:(0,Utils_1.generateMessageIDV2)(null===(d=g.user)||void 0===d?void 0:d.id),fromMe:!1,participant:a.remoteJid},messageStubType:Types_1.WAMessageStubType.GROUP_PARTICIPANT_ADD,
messageStubParameters:[k.creds.me.id],participant:a.remoteJid,messageTimestamp:(0,Utils_1.unixTimestampSeconds)()},"notify");return f.attrs.from}),groupGetInviteInfo:async a=>{a=await e("@g.us","get",[{tag:"invite",attrs:{code:a}}]);return(0,exports.extractGroupMetadata)(a)},groupToggleEphemeral:async(a,b)=>{await e(a,"set",[b?{tag:"ephemeral",attrs:{expiration:b.toString()}}:{tag:"not_ephemeral",attrs:{}}])},groupSettingUpdate:async(a,b)=>{await e(a,"set",[{tag:b,attrs:{}}])},groupMemberAddMode:async(a,
b)=>{await e(a,"set",[{tag:"member_add_mode",attrs:{},content:b}])},groupJoinApprovalMode:async(a,b)=>{await e(a,"set",[{tag:"membership_approval_mode",attrs:{},content:[{tag:"group_join",attrs:{state:b}}]}])},groupFetchAllParticipating:p}};exports.makeGroupsSocket=makeGroupsSocket;
const extractGroupMetadata=c=>{var g,k;c=(0,WABinary_1.getBinaryNodeChild)(c,"group");var h=(0,WABinary_1.getBinaryNodeChild)(c,"description");let l,n;h&&(l=(0,WABinary_1.getBinaryNodeChildString)(h,"body"),n=h.attrs.id);h=c.attrs.id.includes("@")?c.attrs.id:(0,WABinary_1.jidEncode)(c.attrs.id,"g.us");const e=null===(g=(0,WABinary_1.getBinaryNodeChild)(c,"ephemeral"))||void 0===g?void 0:g.attrs.expiration;g="all_member_add"===(0,WABinary_1.getBinaryNodeChildString)(c,"member_add_mode");return{id:h,
addressingMode:c.attrs.addressing_mode,subject:c.attrs.subject,subjectOwner:c.attrs.s_o,subjectTime:+c.attrs.s_t,size:(0,WABinary_1.getBinaryNodeChildren)(c,"participant").length,creation:+c.attrs.creation,owner:c.attrs.creator?(0,WABinary_1.jidNormalizedUser)(c.attrs.creator):void 0,desc:l,descId:n,linkedParent:(null===(k=(0,WABinary_1.getBinaryNodeChild)(c,"linked_parent"))||void 0===k?void 0:k.attrs.jid)||void 0,restrict:!!(0,WABinary_1.getBinaryNodeChild)(c,"locked"),announce:!!(0,WABinary_1.getBinaryNodeChild)(c,
"announcement"),isCommunity:!!(0,WABinary_1.getBinaryNodeChild)(c,"parent"),isCommunityAnnounce:!!(0,WABinary_1.getBinaryNodeChild)(c,"default_sub_group"),joinApprovalMode:!!(0,WABinary_1.getBinaryNodeChild)(c,"membership_approval_mode"),memberAddMode:g,participants:(0,WABinary_1.getBinaryNodeChildren)(c,"participant").map(({attrs:m})=>({id:m.jid,admin:m.type||null})),ephemeralDuration:e?+e:void 0}};exports.extractGroupMetadata=extractGroupMetadata;
