var __importDefault=this&&this.__importDefault||function(p){return p&&p.__esModule?p:{default:p}};Object.defineProperty(exports,"__esModule",{value:!0});exports.makeMessagesSocket=void 0;
const node_cache_1=__importDefault(require("@cacheable/node-cache")),boom_1=require("@hapi/boom"),WAProto_1=require("../../WAProto"),Defaults_1=require("../Defaults"),Utils_1=require("../Utils"),link_preview_1=require("../Utils/link-preview"),WABinary_1=require("../WABinary"),WAUSync_1=require("../WAUSync"),groups_1=require("./groups"),makeMessagesSocket=p=>{const {logger:l,linkPreviewImageThumbnailWidth:la,generateHighQualityLinkPreview:ma,options:na,patchMessageBeforeSending:aa,cachedGroupMetadata:ba}=
p,F=(0,groups_1.makeGroupsSocket)(p),{ev:ca,authState:q,processingMutex:oa,signalRepository:H,upsertMessage:pa,query:L,fetchPrivacySettings:da,sendNode:M,groupMetadata:qa,groupToggleEphemeral:ra}=F,ea=p.userDevicesCache||new node_cache_1.default({stdTTL:Defaults_1.DEFAULT_CACHE_TTLS.USER_DEVICES,useClones:!1});let N;const fa=async(a=!1)=>{const b=await N;if(!b||a||(new Date).getTime()-b.fetchDate.getTime()>1E3*b.ttl)N=(async()=>{var e=await L({tag:"iq",attrs:{type:"set",xmlns:"w:m",to:WABinary_1.S_WHATSAPP_NET},
content:[{tag:"media_conn",attrs:{}}]});e=(0,WABinary_1.getBinaryNodeChild)(e,"media_conn");e={hosts:(0,WABinary_1.getBinaryNodeChildren)(e,"host").map(({attrs:d})=>({hostname:d.hostname,maxContentLengthBytes:+d.maxContentLengthBytes})),auth:e.attrs.auth,ttl:+e.attrs.ttl,fetchDate:new Date};l.debug("fetched media conn");return e})();return N},ha=async(a,b,e,d)=>{const c={tag:"receipt",attrs:{id:e[0]}};if("read"===d||"read-self"===d)c.attrs.t=(0,Utils_1.unixTimestampSeconds)().toString();"sender"===
d&&(0,WABinary_1.isJidUser)(a)?(c.attrs.recipient=a,c.attrs.to=b):(c.attrs.to=a,b&&(c.attrs.participant=b));d&&(c.attrs.type=d);a=e.slice(1);a.length&&(c.content=[{tag:"list",attrs:{},content:a.map(g=>({tag:"item",attrs:{id:g}}))}]);l.debug({attrs:c.attrs,messageIds:e},"sending receipt for messages");await M(c)},ia=async(a,b)=>{a=(0,Utils_1.aggregateMessageKeysNotFromMe)(a);for(const {jid:e,participant:d,messageIds:c}of a)await ha(e,d,c,b)},O=async(a,b,e)=>{var d;const c=[];b||l.debug("not using cache for devices");
var g=[];a=Array.from(new Set(a));for(let f of a)if(a=null===(d=(0,WABinary_1.jidDecode)(f))||void 0===d?void 0:d.user,f=(0,WABinary_1.jidNormalizedUser)(f),b){const m=ea.get(a);m?(c.push(...m),l.trace({user:a},"using cache for devices")):g.push(f)}else g.push(f);if(!g.length)return c;b=(new WAUSync_1.USyncQuery).withContext("message").withDeviceProtocol();for(const f of g)b.withUser((new WAUSync_1.USyncUser).withId(f));if(g=await F.executeUSyncQuery(b)){e=(0,Utils_1.extractDeviceJids)(null===g||
void 0===g?void 0:g.list,q.creds.me.id,e);g={};for(const f of e)g[f.user]=g[f.user]||[],g[f.user].push(f),c.push(f);for(const f in g)ea.set(f,g[f])}return c},P=async(a,b)=>{var e=!1;let d=[];if(b)d=a;else{b=a.map(c=>H.jidToSignalProtocolAddress(c));b=await q.keys.get("session",b);for(const c of a)a=H.jidToSignalProtocolAddress(c),b[a]||d.push(c)}d.length&&(l.debug({jidsRequiringFetch:d},"fetching sessions"),e=await L({tag:"iq",attrs:{xmlns:"encrypt",type:"get",to:WABinary_1.S_WHATSAPP_NET},content:[{tag:"key",
attrs:{},content:d.map(c=>({tag:"user",attrs:{jid:c}}))}]}),await (0,Utils_1.parseAndInjectE2ESessions)(e,H),e=!0);return e},J=async(a,b,e)=>{let d=await aa(b,a);Array.isArray(d)||(d=a?a.map(g=>({recipientJid:g,...d})):[d]);let c=!1;return{nodes:await Promise.all(d.map(async g=>{const {recipientJid:f,...m}=g;if(!f)return{};g=(0,Utils_1.encodeWAMessage)(m);const {type:x,ciphertext:r}=await H.encryptMessage({jid:f,data:g});"pkmsg"===x&&(c=!0);return{tag:"to",attrs:{jid:f},content:[{tag:"enc",attrs:{v:"2",
type:x,...(e||{})},content:r}]}})),shouldIncludeDeviceIdentity:c}},Y=async(a,b,{messageId:e,participant:d,additionalAttributes:c,additionalNodes:g,useUserDevicesCache:f,useCachedGroupMetadata:m,statusJidList:x})=>{var r;const y=q.creds.me.id;let z=!1;const {user:Q,server:ja}=(0,WABinary_1.jidDecode)(a),R="g.us"===ja,u="status@broadcast"===a,S="lid"===ja;e=e||(0,Utils_1.generateMessageIDV2)(null===(r=F.user)||void 0===r?void 0:r.id);f=!1!==f;m=!1!==m&&!u;const A=[],B=u?"status@broadcast":(0,WABinary_1.jidEncode)(Q,
S?"lid":R?"g.us":"s.whatsapp.net"),K=[],C=[],sa={deviceSentMessage:{destinationJid:B,message:b}},I={};if(d){R||u||(c={...c,device_fanout:"false"});const {user:v,device:k}=(0,WABinary_1.jidDecode)(d.jid);C.push({user:v,device:k})}await q.keys.transaction(async()=>{var v,k,D,E=ta(b);E&&(I.mediatype=E);if(null===(v=(0,Utils_1.normalizeMessageContent)(b))||void 0===v?0:v.pinInChatMessage)I["decrypt-fail"]="hide";if(R||u){const [t,G]=await Promise.all([(async()=>{let n=m&&ba?await ba(a):void 0;n&&Array.isArray(null===
n||void 0===n?void 0:n.participants)?l.trace({jid:a,participants:n.participants.length},"using cached group metadata"):u||(n=await qa(a));return n})(),(async()=>d||u?{}:(await q.keys.get("sender-key-memory",[a]))[a]||{})()]);if(!d){var h=t&&!u?t.participants.map(n=>n.id):[];u&&x&&h.push(...x);u||(c={...c,addressing_mode:(null===t||void 0===t?void 0:t.addressingMode)||"pn"});h=await O(h,!!f,!1);C.push(...h)}h=await aa(b);if(Array.isArray(h))throw new boom_1.Boom("Per-jid patching is not supported in groups");
h=(0,Utils_1.encodeWAMessage)(h);const {ciphertext:T,senderKeyDistributionMessage:U}=await H.encryptGroupMessage({group:B,data:h,meId:y});h=[];for(const {user:n,device:V}of C){var w=(0,WABinary_1.jidEncode)(n,"lid"===(null===t||void 0===t?void 0:t.addressingMode)?"lid":"s.whatsapp.net",V);if(!G[w]||d)h.push(w),G[w]=!0}h.length&&(l.debug({senderKeyJids:h},"sending new sender key"),w={senderKeyDistributionMessage:{axolotlSenderKeyDistributionMessage:U,groupId:B}},await P(h,!1),h=await J(h,w,I),z=z||
h.shouldIncludeDeviceIdentity,A.push(...h.nodes));K.push({tag:"enc",attrs:{v:"2",type:"skmsg"},content:T});await q.keys.set({"sender-key-memory":{[a]:G}})}else{({user:v}=(0,WABinary_1.jidDecode)(y));d||(C.push({user:Q}),Q!==v&&C.push({user:v}),"peer"!==(null===c||void 0===c?void 0:c.category)&&(E=await O([y,a],!!f,!0),C.push(...E)));E=[];const t=[],G=[];for(const {user:W,device:ua}of C){const ka=W===v,X=(0,WABinary_1.jidEncode)(ka&&S?(null===(w=null===(h=q.creds)||void 0===h?void 0:h.me)||void 0===
w?void 0:w.lid.split(":")[0])||W:W,S?"lid":"s.whatsapp.net",ua);ka?t.push(X):G.push(X);E.push(X)}await P(E,!1);const [{nodes:T,shouldIncludeDeviceIdentity:U},{nodes:n,shouldIncludeDeviceIdentity:V}]=await Promise.all([J(t,sa,I),J(G,b,I)]);A.push(...T);A.push(...n);z=z||U||V}A.length&&("peer"===(null===c||void 0===c?void 0:c.category)?(h=null===(D=null===(k=A[0])||void 0===k?void 0:k.content)||void 0===D?void 0:D[0])&&K.push(h):K.push({tag:"participants",attrs:{},content:A}));k=e;D=b.pollCreationMessage||
b.pollCreationMessageV2||b.pollCreationMessageV3?"poll":"text";k={tag:"message",attrs:{id:k,type:D,...(c||{})},content:K};d?(0,WABinary_1.isJidGroup)(B)?(k.attrs.to=B,k.attrs.participant=d.jid):(0,WABinary_1.areJidsSameUser)(d.jid,y)?(k.attrs.to=d.jid,k.attrs.recipient=B):k.attrs.to=d.jid:k.attrs.to=B;z&&(k.content.push({tag:"device-identity",attrs:{},content:(0,Utils_1.encodeSignedDeviceIdentity)(q.creds.account,!0)}),l.debug({jid:a},"adding device identity"));g&&0<g.length?k.content.push(...g):
((0,WABinary_1.isJidGroup)(a)||(0,WABinary_1.isJidUser)(a))&&((null===b||void 0===b?0:b.viewOnceMessage)||(null===b||void 0===b?0:b.viewOnceMessageV2)||(null===b||void 0===b?0:b.viewOnceMessageV2Extension)||(null===b||void 0===b?0:b.ephemeralMessage)||(null===b||void 0===b?0:b.templateMessage)||(null===b||void 0===b?0:b.interactiveMessage)||(null===b||void 0===b?0:b.buttonsMessage))&&k.content.push({tag:"biz",attrs:{},content:[{tag:"interactive",attrs:{type:"native_flow",v:"1"},content:[{tag:"native_flow",
attrs:{name:"quick_reply"}}]}]});if(D=va(b))k.content.push({tag:"biz",attrs:{},content:[{tag:D,attrs:wa(b)}]}),l.debug({jid:a},"adding business node");l.debug({msgId:e},`sending message to ${A.length} devices`);await M(k)});return e},ta=a=>{if(a.imageMessage)return"image";if(a.videoMessage)return a.videoMessage.gifPlayback?"gif":"video";if(a.audioMessage)return a.audioMessage.ptt?"ptt":"audio";if(a.contactMessage)return"vcard";if(a.documentMessage)return"document";if(a.contactsArrayMessage)return"contact_array";
if(a.liveLocationMessage)return"livelocation";if(a.stickerMessage)return"sticker";if(a.listMessage)return"list";if(a.listResponseMessage)return"list_response";if(a.buttonsResponseMessage)return"buttons_response";if(a.orderMessage)return"order";if(a.productMessage)return"product";if(a.interactiveResponseMessage)return"native_flow_response";if(a.groupInviteMessage)return"url"},va=a=>{if(a.buttonsMessage)return"buttons";if(a.buttonsResponseMessage)return"buttons_response";if(a.interactiveResponseMessage)return"interactive_response";
if(a.listMessage)return"list";if(a.listResponseMessage)return"list_response"},wa=a=>{if(a.templateMessage)return{};if(a.listMessage){a=a.listMessage.listType;if(!a)throw new boom_1.Boom("Expected list type inside message");return{v:"2",type:ListType[a].toLowerCase()}}return{}},Z=(0,Utils_1.getWAUploadToServer)(p,fa),xa=(0,Utils_1.bindWaitForEvent)(ca,"messages.media-update");return{...F,getPrivacyTokens:async a=>{const b=(0,Utils_1.unixTimestampSeconds)().toString();return await L({tag:"iq",attrs:{to:WABinary_1.S_WHATSAPP_NET,
type:"set",xmlns:"privacy"},content:[{tag:"tokens",attrs:{},content:a.map(e=>({tag:"token",attrs:{jid:(0,WABinary_1.jidNormalizedUser)(e),t:b,type:"trusted_contact"}}))}]})},assertSessions:P,relayMessage:Y,sendReceipt:ha,sendReceipts:ia,readMessages:async a=>{const b="all"===(await da()).readreceipts?"read":"read-self";await ia(a,b)},refreshMediaConn:fa,waUploadToServer:Z,fetchPrivacySettings:da,sendPeerDataOperationMessage:async a=>{var b;if(null===(b=q.creds.me)||void 0===b||!b.id)throw new boom_1.Boom("Not authenticated");
a={protocolMessage:{peerDataOperationRequestMessage:a,type:WAProto_1.proto.Message.ProtocolMessage.Type.PEER_DATA_OPERATION_REQUEST_MESSAGE}};b=(0,WABinary_1.jidNormalizedUser)(q.creds.me.id);return await Y(b,a,{additionalAttributes:{category:"peer",push_priority:"high_force"}})},createParticipantNodes:J,getUSyncDevices:O,updateMediaMessage:async a=>{const b=(0,Utils_1.assertMediaContent)(a.message),e=b.mediaKey,d=await (0,Utils_1.encryptMediaRetryRequest)(a.key,e,q.creds.me.id);let c=void 0;await Promise.all([M(d),
xa(async g=>{if(g=g.find(f=>f.key.id===a.key.id)){if(g.error)c=g.error;else try{const f=await (0,Utils_1.decryptMediaRetryData)(g.media,e,g.key.id);if(f.result!==WAProto_1.proto.MediaRetryNotification.ResultType.SUCCESS)throw new boom_1.Boom(`Media re-upload failed by device (${WAProto_1.proto.MediaRetryNotification.ResultType[f.result]})`,{data:f,statusCode:(0,Utils_1.getStatusCodeForMediaRetry)(f.result)||404});b.directPath=f.directPath;b.url=(0,Utils_1.getUrlFromDirectPath)(b.directPath);l.debug({directPath:f.directPath,
key:g.key},"media update successful")}catch(f){c=f}return!0}})]);if(c)throw c;ca.emit("messages.update",[{key:a.key,update:{message:a.message}}]);return a},sendMessage:async(a,b,e={})=>{var d,c,g,f=q.creds.me.id;if("object"===typeof b&&"disappearingMessagesInChat"in b&&"undefined"!==typeof b.disappearingMessagesInChat&&(0,WABinary_1.isJidGroup)(a))({disappearingMessagesInChat:b}=b),await ra(a,"boolean"===typeof b?b?Defaults_1.WA_DEFAULT_EPHEMERAL:0:b);else{const m=await (0,Utils_1.generateWAMessage)(a,
b,{logger:l,userJid:f,getUrlInfo:z=>(0,link_preview_1.getUrlInfo)(z,{thumbnailWidth:la,fetchOpts:{timeout:3E3,...(na||{})},logger:l,uploadImage:ma?Z:void 0}),getProfilePicUrl:F.profilePictureUrl,upload:Z,mediaCache:p.mediaCache,options:p.options,messageId:(0,Utils_1.generateMessageIDV2)(null===(d=F.user)||void 0===d?void 0:d.id),...e});d="edit"in b&&!!b.edit;f="pin"in b&&!!b.pin;const x="poll"in b&&!!b.poll,r={},y=[];"delete"in b&&b.delete?!(0,WABinary_1.isJidGroup)(null===(c=b.delete)||void 0===
c?void 0:c.remoteJid)||(null===(g=b.delete)||void 0===g?0:g.fromMe)?r.edit="7":r.edit="8":d?r.edit="1":f?r.edit="2":x&&y.push({tag:"meta",attrs:{polltype:"creation"}});"cachedGroupMetadata"in e&&console.warn("cachedGroupMetadata in sendMessage are deprecated, now cachedGroupMetadata is part of the socket config.");await Y(a,m.message,{messageId:m.key.id,useCachedGroupMetadata:e.useCachedGroupMetadata,additionalAttributes:r,statusJidList:e.statusJidList,additionalNodes:y});p.emitOwnEvents&&process.nextTick(()=>
{oa.mutex(()=>pa(m,"append"))});return m}}}};exports.makeMessagesSocket=makeMessagesSocket;
