Object.defineProperty(exports,"__esModule",{value:!0});exports.uploadingNecessaryImages=exports.parseProductNode=exports.toProductNode=exports.parseOrderDetailsNode=exports.parseCollectionsNode=exports.parseCatalogNode=void 0;exports.uploadingNecessaryImagesOfProduct=uploadingNecessaryImagesOfProduct;
const boom_1=require("@hapi/boom"),crypto_1=require("crypto"),fs_1=require("fs"),os_1=require("os"),path_1=require("path"),WABinary_1=require("../WABinary"),generics_1=require("./generics"),messages_media_1=require("./messages-media"),parseCatalogNode=a=>{var b=(0,WABinary_1.getBinaryNodeChild)(a,"product_catalog");a=(0,WABinary_1.getBinaryNodeChildren)(b,"product").map(exports.parseProductNode);b=(0,WABinary_1.getBinaryNodeChild)(b,"paging");return{products:a,nextPageCursor:b?(0,WABinary_1.getBinaryNodeChildString)(b,
"after"):void 0}};exports.parseCatalogNode=parseCatalogNode;const parseCollectionsNode=a=>{a=(0,WABinary_1.getBinaryNodeChild)(a,"collections");return{collections:(0,WABinary_1.getBinaryNodeChildren)(a,"collection").map(b=>{const d=(0,WABinary_1.getBinaryNodeChildString)(b,"id"),c=(0,WABinary_1.getBinaryNodeChildString)(b,"name"),e=(0,WABinary_1.getBinaryNodeChildren)(b,"product").map(exports.parseProductNode);return{id:d,name:c,products:e,status:parseStatusInfo(b)}})}};
exports.parseCollectionsNode=parseCollectionsNode;
const parseOrderDetailsNode=a=>{var b=(0,WABinary_1.getBinaryNodeChild)(a,"order");a=(0,WABinary_1.getBinaryNodeChildren)(b,"product").map(d=>{const c=(0,WABinary_1.getBinaryNodeChild)(d,"image");return{id:(0,WABinary_1.getBinaryNodeChildString)(d,"id"),name:(0,WABinary_1.getBinaryNodeChildString)(d,"name"),imageUrl:(0,WABinary_1.getBinaryNodeChildString)(c,"url"),price:+(0,WABinary_1.getBinaryNodeChildString)(d,"price"),currency:(0,WABinary_1.getBinaryNodeChildString)(d,"currency"),quantity:+(0,WABinary_1.getBinaryNodeChildString)(d,
"quantity")}});b=(0,WABinary_1.getBinaryNodeChild)(b,"price");return{price:{total:+(0,WABinary_1.getBinaryNodeChildString)(b,"total"),currency:(0,WABinary_1.getBinaryNodeChildString)(b,"currency")},products:a}};exports.parseOrderDetailsNode=parseOrderDetailsNode;
const toProductNode=(a,b)=>{const d={},c=[];"undefined"!==typeof a&&c.push({tag:"id",attrs:{},content:Buffer.from(a)});"undefined"!==typeof b.name&&c.push({tag:"name",attrs:{},content:Buffer.from(b.name)});"undefined"!==typeof b.description&&c.push({tag:"description",attrs:{},content:Buffer.from(b.description)});"undefined"!==typeof b.retailerId&&c.push({tag:"retailer_id",attrs:{},content:Buffer.from(b.retailerId)});b.images.length&&c.push({tag:"media",attrs:{},content:b.images.map(e=>{if(!("url"in
e))throw new boom_1.Boom("Expected img for product to already be uploaded",{statusCode:400});return{tag:"image",attrs:{},content:[{tag:"url",attrs:{},content:Buffer.from(e.url.toString())}]}})});"undefined"!==typeof b.price&&c.push({tag:"price",attrs:{},content:Buffer.from(b.price.toString())});"undefined"!==typeof b.currency&&c.push({tag:"currency",attrs:{},content:Buffer.from(b.currency)});"originCountryCode"in b&&("undefined"===typeof b.originCountryCode?d.compliance_category="COUNTRY_ORIGIN_EXEMPT":
c.push({tag:"compliance_info",attrs:{},content:[{tag:"country_code_origin",attrs:{},content:Buffer.from(b.originCountryCode)}]}));"undefined"!==typeof b.isHidden&&(d.is_hidden=b.isHidden.toString());return{tag:"product",attrs:d,content:c}};exports.toProductNode=toProductNode;
const parseProductNode=a=>{const b="true"===a.attrs.is_hidden,d=(0,WABinary_1.getBinaryNodeChildString)(a,"id"),c=(0,WABinary_1.getBinaryNodeChild)(a,"media"),e=(0,WABinary_1.getBinaryNodeChild)(a,"status_info");return{id:d,imageUrls:parseImageUrls(c),reviewStatus:{whatsapp:(0,WABinary_1.getBinaryNodeChildString)(e,"status")},availability:"in stock",name:(0,WABinary_1.getBinaryNodeChildString)(a,"name"),retailerId:(0,WABinary_1.getBinaryNodeChildString)(a,"retailer_id"),url:(0,WABinary_1.getBinaryNodeChildString)(a,
"url"),description:(0,WABinary_1.getBinaryNodeChildString)(a,"description"),price:+(0,WABinary_1.getBinaryNodeChildString)(a,"price"),currency:(0,WABinary_1.getBinaryNodeChildString)(a,"currency"),isHidden:b}};exports.parseProductNode=parseProductNode;async function uploadingNecessaryImagesOfProduct(a,b,d=3E4){return a={...a,images:a.images?await (0,exports.uploadingNecessaryImages)(a.images,b,d):a.images}}
const uploadingNecessaryImages=async(a,b,d=3E4)=>await Promise.all(a.map(async c=>{if("url"in c){var e=c.url.toString();if(e.includes(".whatsapp.net"))return{url:e}}({stream:e}=await (0,messages_media_1.getStream)(c));const g=(0,crypto_1.createHash)("sha256");c=(0,path_1.join)((0,os_1.tmpdir)(),"img"+(0,generics_1.generateMessageIDV2)());const h=(0,fs_1.createWriteStream)(c);for await(var f of e)g.update(f),h.write(f);f=g.digest("base64");({directPath:f}=await b(c,{mediaType:"product-catalog-image",
fileEncSha256B64:f,timeoutMs:d}));await fs_1.promises.unlink(c).catch(k=>console.log("Error deleting temp file ",k));return{url:(0,messages_media_1.getUrlFromDirectPath)(f)}}));exports.uploadingNecessaryImages=uploadingNecessaryImages;
const parseImageUrls=a=>{a=(0,WABinary_1.getBinaryNodeChild)(a,"image");return{requested:(0,WABinary_1.getBinaryNodeChildString)(a,"request_image_url"),original:(0,WABinary_1.getBinaryNodeChildString)(a,"original_image_url")}},parseStatusInfo=a=>{a=(0,WABinary_1.getBinaryNodeChild)(a,"status_info");return{status:(0,WABinary_1.getBinaryNodeChildString)(a,"status"),canAppeal:"true"===(0,WABinary_1.getBinaryNodeChildString)(a,"can_appeal")}};
