var __importDefault=this&&this.__importDefault||function(a){return a&&a.__esModule?a:{"default":a}};Object.defineProperty(exports,"__esModule",{value:!0});
exports.assertMediaContent=exports.downloadMediaMessage=exports.aggregateMessageKeysNotFromMe=exports.updateMessageWithPollUpdate=exports.updateMessageWithReaction=exports.updateMessageWithReceipt=exports.getDevice=exports.extractMessageContent=exports.normalizeMessageContent=exports.getContentType=exports.generateWAMessage=exports.generateWAMessageFromContent=exports.generateWAMessageContent=exports.generateForwardMessageContent=exports.prepareDisappearingMessageSettingContent=exports.prepareWAMessageMedia=
exports.generateLinkPreviewIfRequired=exports.extractUrlFromText=void 0;exports.getAggregateVotesInPollMessage=getAggregateVotesInPollMessage;
const boom_1=require("@hapi/boom"),axios_1=__importDefault(require("axios")),crypto_1=require("crypto"),fs_1=require("fs"),WAProto_1=require("../../WAProto"),Defaults_1=require("../Defaults"),Types_1=require("../Types"),WABinary_1=require("../WABinary"),crypto_2=require("./crypto"),generics_1=require("./generics"),messages_media_1=require("./messages-media"),MIMETYPE_MAP={image:"image/jpeg",video:"video/mp4",document:"application/pdf",audio:"audio/ogg; codecs=opus",sticker:"image/webp","product-catalog-image":"image/jpeg"},
MessageTypeProto={image:Types_1.WAProto.Message.ImageMessage,video:Types_1.WAProto.Message.VideoMessage,audio:Types_1.WAProto.Message.AudioMessage,sticker:Types_1.WAProto.Message.StickerMessage,document:Types_1.WAProto.Message.DocumentMessage},ButtonType=WAProto_1.proto.Message.ButtonsMessage.HeaderType,extractUrlFromText=a=>{var c;return null===(c=a.match(Defaults_1.URL_REGEX))||void 0===c?void 0:c[0]};exports.extractUrlFromText=extractUrlFromText;
const generateLinkPreviewIfRequired=async(a,c,d)=>{a=(0,exports.extractUrlFromText)(a);if(c&&a)try{return await c(a)}catch(b){null===d||void 0===d||d.warn({trace:b.stack},"url generation failed")}};exports.generateLinkPreviewIfRequired=generateLinkPreviewIfRequired;
const assertColor=async a=>{if("number"!==typeof a)return a=a.trim().replace("#",""),6>=a.length&&(a="FF"+a.padStart(6,"0")),a=parseInt(a,16)},prepareWAMessageMedia=async(a,c)=>{const d=c.logger;let b;for(const l of Defaults_1.MEDIA_KEYS)l in a&&(b=l);if(!b)throw new boom_1.Boom("Invalid media type",{statusCode:400});const e={...a,media:a[b]};delete e[b];const f="object"===typeof e.media&&"url"in e.media&&!!e.media.url&&!!c.mediaCache&&b+":"+e.media.url.toString();"document"!==b||e.fileName||(e.fileName=
"file");e.mimetype||(e.mimetype=MIMETYPE_MAP[b]);if(f&&(a=c.mediaCache.get(f)))return null===d||void 0===d||d.debug({cacheableKey:f},"got media cache hit"),a=Types_1.WAProto.Message.decode(a),Object.assign(a[`${b}Message`],{...e,media:void 0}),a;const g="audio"===b&&"undefined"===typeof e.seconds,k=("image"===b||"video"===b)&&"undefined"===typeof e.jpegThumbnail,h="audio"===b&&!0===e.ptt,p=c.backgroundColor&&"audio"===b&&!0===e.ptt,{mediaKey:m,encWriteStream:r,bodyPath:n,fileEncSha256:t,fileSha256:u,
fileLength:v,didSaveToTmpPath:w}=await (0,messages_media_1.encryptedStream)(e.media,c.mediaTypeOverride||b,{logger:d,saveOriginalFileIfRequired:g||k,opts:c.options}),x=t.toString("base64"),[{mediaUrl:y,directPath:z}]=await Promise.all([(async()=>{const l=await c.upload(r,{fileEncSha256B64:x,mediaType:b,timeoutMs:c.mediaUploadTimeoutMs});null===d||void 0===d||d.debug({mediaType:b,cacheableKey:f},"uploaded media");return l})(),(async()=>{try{if(k){const {thumbnail:l,originalImageDimensions:q}=await (0,messages_media_1.generateThumbnail)(n,
b,c);e.jpegThumbnail=l;!e.width&&q&&(e.width=q.width,e.height=q.height,null===d||void 0===d||d.debug("set dimensions"));null===d||void 0===d||d.debug("generated thumbnail")}g&&(e.seconds=await (0,messages_media_1.getAudioDuration)(n),null===d||void 0===d||d.debug("computed audio duration"));h&&(e.waveform=await (0,messages_media_1.getAudioWaveform)(n,d),null===d||void 0===d||d.debug("processed waveform"));p&&(e.backgroundArgb=await assertColor(c.backgroundColor),null===d||void 0===d||d.debug("computed backgroundColor audio status"))}catch(l){null===
d||void 0===d||d.warn({trace:l.stack},"failed to obtain extra info")}})()]).finally(async()=>{r.destroy();if(w&&n)try{await fs_1.promises.access(n),await fs_1.promises.unlink(n),null===d||void 0===d||d.debug("removed tmp file")}catch(l){null===d||void 0===d||d.warn("failed to remove tmp file")}});a=Types_1.WAProto.Message.fromObject({[`${b}Message`]:MessageTypeProto[b].fromObject({url:y,directPath:z,mediaKey:m,fileEncSha256:t,fileSha256:u,fileLength:v,mediaKeyTimestamp:(0,generics_1.unixTimestampSeconds)(),
...e,media:void 0})});e.ptv&&(a.ptvMessage=a.videoMessage,delete a.videoMessage);f&&(null===d||void 0===d||d.debug({cacheableKey:f},"set cache"),c.mediaCache.set(f,Types_1.WAProto.Message.encode(a).finish()));return a};exports.prepareWAMessageMedia=prepareWAMessageMedia;const prepareDisappearingMessageSettingContent=a=>Types_1.WAProto.Message.fromObject({ephemeralMessage:{message:{protocolMessage:{type:Types_1.WAProto.Message.ProtocolMessage.Type.EPHEMERAL_SETTING,ephemeralExpiration:a||0}}}});
exports.prepareDisappearingMessageSettingContent=prepareDisappearingMessageSettingContent;
const generateForwardMessageContent=(a,c)=>{var d;let b=a.message;if(!b)throw new boom_1.Boom("no content in message",{statusCode:400});b=(0,exports.normalizeMessageContent)(b);b=WAProto_1.proto.Message.decode(WAProto_1.proto.Message.encode(b).finish());let e=Object.keys(b)[0],f=(null===(d=b[e].contextInfo)||void 0===d?void 0:d.forwardingScore)||0;f+=a.key.fromMe&&!c?0:1;"conversation"===e&&(b.extendedTextMessage={text:b[e]},delete b.conversation,e="extendedTextMessage");b[e].contextInfo=0<f?{forwardingScore:f,
isForwarded:!0}:{};return b};exports.generateForwardMessageContent=generateForwardMessageContent;
const generateWAMessageContent=async(a,c)=>{var d;let b={};if("text"in a){var e={text:a.text};var f=a.linkPreview;"undefined"===typeof f&&(f=await (0,exports.generateLinkPreviewIfRequired)(a.text,c.getUrlInfo,c.logger));f&&(e.matchedText=f["matched-text"],e.jpegThumbnail=f.jpegThumbnail,e.description=f.description,e.title=f.title,e.previewType=0,f=f.highQualityThumbnail)&&(e.thumbnailDirectPath=f.directPath,e.mediaKey=f.mediaKey,e.mediaKeyTimestamp=f.mediaKeyTimestamp,e.thumbnailWidth=f.width,e.thumbnailHeight=
f.height,e.thumbnailSha256=f.fileSha256,e.thumbnailEncSha256=f.fileEncSha256);c.backgroundColor&&(e.backgroundArgb=await assertColor(c.backgroundColor));c.font&&(e.font=c.font);b.extendedTextMessage=e}else if("contacts"in a){c=a.contacts.contacts.length;if(!c)throw new boom_1.Boom("require atleast 1 contact",{statusCode:400});1===c?b.contactMessage=Types_1.WAProto.Message.ContactMessage.fromObject(a.contacts.contacts[0]):b.contactsArrayMessage=Types_1.WAProto.Message.ContactsArrayMessage.fromObject(a.contacts)}else if("location"in
a)b.locationMessage=Types_1.WAProto.Message.LocationMessage.fromObject(a.location);else if("react"in a)a.react.senderTimestampMs||(a.react.senderTimestampMs=Date.now()),b.reactionMessage=Types_1.WAProto.Message.ReactionMessage.fromObject(a.react);else if("delete"in a)b.protocolMessage={key:a.delete,type:Types_1.WAProto.Message.ProtocolMessage.Type.REVOKE};else if("forward"in a)b=(0,exports.generateForwardMessageContent)(a.forward,a.force);else if("disappearingMessagesInChat"in a)b=(0,exports.prepareDisappearingMessageSettingContent)("boolean"===
typeof a.disappearingMessagesInChat?a.disappearingMessagesInChat?Defaults_1.WA_DEFAULT_EPHEMERAL:0:a.disappearingMessagesInChat);else if("groupInvite"in a){if(b.groupInviteMessage={},b.groupInviteMessage.inviteCode=a.groupInvite.inviteCode,b.groupInviteMessage.inviteExpiration=a.groupInvite.inviteExpiration,b.groupInviteMessage.caption=a.groupInvite.text,b.groupInviteMessage.groupJid=a.groupInvite.jid,b.groupInviteMessage.groupName=a.groupInvite.subject,c.getProfilePicUrl&&(c=await c.getProfilePicUrl(a.groupInvite.jid,
"preview")))c=await axios_1.default.get(c,{responseType:"arraybuffer"}),200===c.status&&(b.groupInviteMessage.jpegThumbnail=c.data)}else if("pin"in a)b.pinInChatMessage={},b.messageContextInfo={},b.pinInChatMessage.key=a.pin,b.pinInChatMessage.type=a.type,b.pinInChatMessage.senderTimestampMs=Date.now(),b.messageContextInfo.messageAddOnDurationInSecs=1===a.type?a.time||86400:0;else if("buttonReply"in a)switch(a.type){case "template":b.templateButtonReplyMessage={selectedDisplayText:a.buttonReply.displayText,
selectedId:a.buttonReply.id,selectedIndex:a.buttonReply.index};break;case "plain":b.buttonsResponseMessage={selectedButtonId:a.buttonReply.id,selectedDisplayText:a.buttonReply.displayText,type:WAProto_1.proto.Message.ButtonsResponseMessage.Type.DISPLAY_TEXT}}else if("ptv"in a&&a.ptv)({videoMessage:c}=await (0,exports.prepareWAMessageMedia)({video:a.video},c)),b.ptvMessage=c;else if("product"in a)({imageMessage:c}=await (0,exports.prepareWAMessageMedia)({image:a.product.productImage},c)),b.productMessage=
Types_1.WAProto.Message.ProductMessage.fromObject({...a,product:{...a.product,productImage:c}});else if("listReply"in a)b.listResponseMessage={...a.listReply};else if("poll"in a){(e=a.poll).selectableCount||(e.selectableCount=0);(f=a.poll).toAnnouncementGroup||(f.toAnnouncementGroup=!1);if(!Array.isArray(a.poll.values))throw new boom_1.Boom("Invalid poll values",{statusCode:400});if(0>a.poll.selectableCount||a.poll.selectableCount>a.poll.values.length)throw new boom_1.Boom(`poll.selectableCount in poll should be >= 0 and <= ${a.poll.values.length}`,
{statusCode:400});b.messageContextInfo={messageSecret:a.poll.messageSecret||(0,crypto_1.randomBytes)(32)};c={name:a.poll.name,selectableOptionsCount:a.poll.selectableCount,options:a.poll.values.map(g=>({optionName:g}))};a.poll.toAnnouncementGroup?b.pollCreationMessageV2=c:0<a.poll.selectableCount?b.pollCreationMessageV3=c:b.pollCreationMessage=c}else"sharePhoneNumber"in a?b.protocolMessage={type:WAProto_1.proto.Message.ProtocolMessage.Type.SHARE_PHONE_NUMBER}:"requestPhoneNumber"in a?b.requestPhoneNumberMessage=
{}:b=await (0,exports.prepareWAMessageMedia)(a,c);"buttons"in a&&a.buttons?(c={buttons:a.buttons.map(g=>({...g,type:WAProto_1.proto.Message.ButtonsMessage.Button.Type.RESPONSE}))},"text"in a?(c.contentText=a.text,c.headerType=ButtonType.EMPTY):("caption"in a&&(c.contentText=a.caption),e=Object.keys(b)[0].replace("Message","").toUpperCase(),c.headerType=ButtonType[e],Object.assign(c,b)),"footer"in a&&a.footer&&(c.footerText=a.footer),b={buttonsMessage:c}):"templateButtons"in a&&a.templateButtons&&
(c={hydratedButtons:a.templateButtons},"text"in a?c.hydratedContentText=a.text:("caption"in a&&(c.hydratedContentText=a.caption),Object.assign(c,b)),"footer"in a&&a.footer&&(c.hydratedFooterText=a.footer),b={templateMessage:{fourRowTemplate:c,hydratedTemplate:c}});"sections"in a&&a.sections&&(b={listMessage:{sections:a.sections,buttonText:a.buttonText,title:a.title,footerText:a.footer,description:a.text,listType:WAProto_1.proto.Message.ListMessage.ListType.SINGLE_SELECT}});"viewOnce"in a&&a.viewOnce&&
(b={viewOnceMessage:{message:b}});"mentions"in a&&(null===(d=a.mentions)||void 0===d?0:d.length)&&([d]=Object.keys(b),b[d].contextInfo=b[d]||{},b[d].contextInfo.mentionedJid=a.mentions);"edit"in a&&(b={protocolMessage:{key:a.edit,editedMessage:b,timestampMs:Date.now(),type:Types_1.WAProto.Message.ProtocolMessage.Type.MESSAGE_EDIT}});"contextInfo"in a&&a.contextInfo&&([d]=Object.keys(b),b[d]=b[d]||{},b[d].contextInfo=a.contextInfo);return Types_1.WAProto.Message.fromObject(b)};
exports.generateWAMessageContent=generateWAMessageContent;
const generateWAMessageFromContent=(a,c,d)=>{d.timestamp||(d.timestamp=new Date);const b=(0,exports.normalizeMessageContent)(c),e=(0,exports.getContentType)(b),f=(0,generics_1.unixTimestampSeconds)(d.timestamp),{quoted:g,userJid:k}=d;if(g){const p=g.key.fromMe?k:g.participant||g.key.participant||g.key.remoteJid;let m=(0,exports.normalizeMessageContent)(g.message);var h=(0,exports.getContentType)(m);m=WAProto_1.proto.Message.fromObject({[h]:m[h]});h=m[h];"object"===typeof h&&h&&"contextInfo"in h&&
delete h.contextInfo;h=b[e].contextInfo||{};h.participant=(0,WABinary_1.jidNormalizedUser)(p);h.stanzaId=g.key.id;h.quotedMessage=m;a!==g.key.remoteJid&&(h.remoteJid=g.key.remoteJid);b[e].contextInfo=h}(null===d||void 0===d?0:d.ephemeralExpiration)&&"protocolMessage"!==e&&"ephemeralMessage"!==e&&(b[e].contextInfo={...(b[e].contextInfo||{}),expiration:d.ephemeralExpiration||Defaults_1.WA_DEFAULT_EPHEMERAL});c=Types_1.WAProto.Message.fromObject(c);a={key:{remoteJid:a,fromMe:!0,id:(null===d||void 0===
d?void 0:d.messageId)||(0,generics_1.generateMessageIDV2)()},message:c,messageTimestamp:f,messageStubParameters:[],participant:(0,WABinary_1.isJidGroup)(a)||(0,WABinary_1.isJidStatusBroadcast)(a)?k:void 0,status:Types_1.WAMessageStatus.PENDING};return Types_1.WAProto.WebMessageInfo.fromObject(a)};exports.generateWAMessageFromContent=generateWAMessageFromContent;
const generateWAMessage=async(a,c,d)=>{var b;d.logger=null===(b=null===d||void 0===d?void 0:d.logger)||void 0===b?void 0:b.child({msgId:d.messageId});return(0,exports.generateWAMessageFromContent)(a,await (0,exports.generateWAMessageContent)(c,d),d)};exports.generateWAMessage=generateWAMessage;const getContentType=a=>{if(a)return Object.keys(a).find(c=>("conversation"===c||c.includes("Message"))&&"senderKeyDistributionMessage"!==c)};exports.getContentType=getContentType;
const normalizeMessageContent=a=>{if(a){for(let c=0;5>c;c++){const d=(null===a||void 0===a?void 0:a.ephemeralMessage)||(null===a||void 0===a?void 0:a.viewOnceMessage)||(null===a||void 0===a?void 0:a.documentWithCaptionMessage)||(null===a||void 0===a?void 0:a.viewOnceMessageV2)||(null===a||void 0===a?void 0:a.viewOnceMessageV2Extension)||(null===a||void 0===a?void 0:a.editedMessage);if(!d)break;a=d.message}return a}};exports.normalizeMessageContent=normalizeMessageContent;
const extractMessageContent=a=>{var c,d,b,e,f,g;const k=h=>h.imageMessage?{imageMessage:h.imageMessage}:h.documentMessage?{documentMessage:h.documentMessage}:h.videoMessage?{videoMessage:h.videoMessage}:h.locationMessage?{locationMessage:h.locationMessage}:{conversation:"contentText"in h?h.contentText:"hydratedContentText"in h?h.hydratedContentText:""};a=(0,exports.normalizeMessageContent)(a);return(null===a||void 0===a?0:a.buttonsMessage)?k(a.buttonsMessage):(null===(c=null===a||void 0===a?void 0:
a.templateMessage)||void 0===c?0:c.hydratedFourRowTemplate)?k(null===(d=null===a||void 0===a?void 0:a.templateMessage)||void 0===d?void 0:d.hydratedFourRowTemplate):(null===(b=null===a||void 0===a?void 0:a.templateMessage)||void 0===b?0:b.hydratedTemplate)?k(null===(e=null===a||void 0===a?void 0:a.templateMessage)||void 0===e?void 0:e.hydratedTemplate):(null===(f=null===a||void 0===a?void 0:a.templateMessage)||void 0===f?0:f.fourRowTemplate)?k(null===(g=null===a||void 0===a?void 0:a.templateMessage)||
void 0===g?void 0:g.fourRowTemplate):a};exports.extractMessageContent=extractMessageContent;const getDevice=a=>/^3A.{18}$/.test(a)?"ios":/^3E.{20}$/.test(a)?"web":/^(.{21}|.{32})$/.test(a)?"android":/^(3F|.{18}$)/.test(a)?"desktop":"unknown";exports.getDevice=getDevice;const updateMessageWithReceipt=(a,c)=>{a.userReceipt=a.userReceipt||[];const d=a.userReceipt.find(b=>b.userJid===c.userJid);d?Object.assign(d,c):a.userReceipt.push(c)};exports.updateMessageWithReceipt=updateMessageWithReceipt;
const updateMessageWithReaction=(a,c)=>{const d=(0,generics_1.getKeyAuthor)(c.key),b=(a.reactions||[]).filter(e=>(0,generics_1.getKeyAuthor)(e.key)!==d);c.text&&b.push(c);a.reactions=b};exports.updateMessageWithReaction=updateMessageWithReaction;
const updateMessageWithPollUpdate=(a,c)=>{var d,b;const e=(0,generics_1.getKeyAuthor)(c.pollUpdateMessageKey),f=(a.pollUpdates||[]).filter(g=>(0,generics_1.getKeyAuthor)(g.pollUpdateMessageKey)!==e);(null===(b=null===(d=c.vote)||void 0===d?void 0:d.selectedOptions)||void 0===b?0:b.length)&&f.push(c);a.pollUpdates=f};exports.updateMessageWithPollUpdate=updateMessageWithPollUpdate;
function getAggregateVotesInPollMessage({message:a,pollUpdates:c},d){var b,e,f;const g=((null===(b=null===a||void 0===a?void 0:a.pollCreationMessage)||void 0===b?void 0:b.options)||(null===(e=null===a||void 0===a?void 0:a.pollCreationMessageV2)||void 0===e?void 0:e.options)||(null===(f=null===a||void 0===a?void 0:a.pollCreationMessageV3)||void 0===f?void 0:f.options)||[]).reduce((k,h)=>{const p=(0,crypto_2.sha256)(Buffer.from(h.optionName||"")).toString();k[p]={name:h.optionName||"",voters:[]};return k},
{});for(const k of c||[])if({vote:a}=k,a)for(const h of a.selectedOptions||[])a=h.toString(),c=g[a],c||(g[a]={name:"Unknown",voters:[]},c=g[a]),g[a].voters.push((0,generics_1.getKeyAuthor)(k.pollUpdateMessageKey,d));return Object.values(g)}const aggregateMessageKeysNotFromMe=a=>{const c={};for(const {remoteJid:d,id:b,participant:e,fromMe:f}of a)f||(a=`${d}:${e||""}`,c[a]||(c[a]={jid:d,participant:e,messageIds:[]}),c[a].messageIds.push(b));return Object.values(c)};
exports.aggregateMessageKeysNotFromMe=aggregateMessageKeysNotFromMe;
const REUPLOAD_REQUIRED_STATUS=[410,404],downloadMediaMessage=async(a,c,d,b)=>{async function e(){var f=(0,exports.extractMessageContent)(a.message);if(!f)throw new boom_1.Boom("No message present",{statusCode:400,data:a});var g=(0,exports.getContentType)(f),k=null===g||void 0===g?void 0:g.replace("Message","");f=f[g];if(!f||"object"!==typeof f||!("url"in f||"thumbnailDirectPath"in f))throw new boom_1.Boom(`"${g}" message is not a media message`);"thumbnailDirectPath"in f&&!("url"in f)?(g={directPath:f.thumbnailDirectPath,
mediaKey:f.mediaKey},k="thumbnail-link"):g=f;k=await (0,messages_media_1.downloadContentFromMessage)(g,k,d);if("buffer"===c){g=[];for await(const h of k)g.push(h);return Buffer.concat(g)}return k}return await e().catch(async f=>{var g;if(b&&axios_1.default.isAxiosError(f)&&REUPLOAD_REQUIRED_STATUS.includes(null===(g=f.response)||void 0===g?void 0:g.status))return b.logger.info({key:a.key},"sending reupload media request..."),a=await b.reuploadRequest(a),await e();throw f;})};
exports.downloadMediaMessage=downloadMediaMessage;const assertMediaContent=a=>{a=(0,exports.extractMessageContent)(a);const c=(null===a||void 0===a?void 0:a.documentMessage)||(null===a||void 0===a?void 0:a.imageMessage)||(null===a||void 0===a?void 0:a.videoMessage)||(null===a||void 0===a?void 0:a.audioMessage)||(null===a||void 0===a?void 0:a.stickerMessage);if(!c)throw new boom_1.Boom("given message is not a media message",{statusCode:400,data:a});return c};exports.assertMediaContent=assertMediaContent;
